### ISSUE TITLE
Rewrite in Brainfuck

### ISSUE THREAD

**Issue by Scrumplex** [dada513/potatencoder#1]
I do not have the hardware to run this complex JS code. Can you rewrite it in something more lightweight like Brainfuck?

**Comment by DioEgizio** [comment]
Rewrite in rust, the based language instead

**Comment by flowln** [comment]
This project has too many dependencies. I would suggest we create a new PotatLang language for it instead.

**Comment by DioEgizio** [comment]
based

**Comment by Scrumplex** [comment]
#3 might improve the situation a bit.

**Comment by dada513** [comment]
After taking this issue into full consideration, I have decided that your mother
